// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Proto.Actor.FSharp")>]
[<assembly: AssemblyProductAttribute("protoactor-fsharp")>]
[<assembly: AssemblyDescriptionAttribute("F# API for proto.actor")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Proto.Actor.FSharp"
    let [<Literal>] AssemblyProduct = "protoactor-fsharp"
    let [<Literal>] AssemblyDescription = "F# API for proto.actor"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
